# Generated by Django 1.11.3 on 2017-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gore', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
