# Generated by Django 1.11.4 on 2018-06-25 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gore', '0003_event_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_hash', models.CharField(max_length=64)),
                ('first_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gore.Event')),
                ('first_event_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_event_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('n_events', models.IntegerField(default=0, editable=False)),
                ('archived', models.BooleanField(default=False, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gore.Project')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='gore.EventGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='eventgroup',
            unique_together={('project', 'group_hash')},
        ),
    ]
