# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 15:32
from __future__ import unicode_literals

from django.db import migrations, transaction

from gore.utils.event_grouper import group_events


def group_all_events(apps, schema_editor):
    from gore.models import Project
    with transaction.atomic():
        for project in Project.objects.all():  # Using apps.get_model() won't work here.
            events = project.event_set.all().order_by('timestamp')
            group_events(project, events)


class Migration(migrations.Migration):
    dependencies = [
        ('gore', '0004_event_group'),
    ]

    operations = [
        migrations.RunPython(
            group_all_events,
            migrations.RunPython.noop,
        )
    ]
