[tool.ruff]
exclude = [
    "*node_modules*",
]

line-length = 120

[tool.ruff.format]
preview = true
quote-style = "preserve"

[tool.ruff.lint]
extend-select = [
    "C9",
    "E",
    "F",
    "I",
    "W",
]
ignore = ["E722"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "gentry.settings"
