# flake8: noqa
log_payload = """
{"level": 30, "logger": "zTNXk5vQCfK4", "tags": {}, "extra": {"sys.argv": ["'/virtualenv/bin/py.test'", "'gore'", "'-vvv'", "'--cov'", "'.'", "'--cov-report'", "'html'"], "pathname": "'/code/gore/tests/test_send.py'", "filename": "'test_send.py'", "stack_info": null, "lineno": 44, "thread": 140737291113408, "threadName": "'MainThread'", "processName": "'MainProcess'", "process": 38289}, "sentry.interfaces.Message": {"message": "Oh no!", "params": [], "formatted": "Oh no!"}, "message": "Oh no!", "server_name": "Gaea.local", "modules": {"python": "3.6.0"}, "project": "1", "timestamp": "2017-07-24T16:33:57Z", "time_spent": null, "event_id": "d51329934dba43408bea8e1e20c54c9c", "platform": "python", "sdk": {"name": "raven-python", "version": "6.1.0"}, "repos": {}, "breadcrumbs": {"values": [{"type": "default", "timestamp": 1500914037.6322172, "level": "warning", "message": "Oh no!", "category": "zTNXk5vQCfK4", "data": {}}]}}
""".strip()
exc_payload = """
{"tags": {}, "extra": {"sys.argv": ["'/virtualenv/bin/py.test'", "'gore'", "'-vvv'", "'--cov'", "'.'", "'--cov-report'", "'html'"]}, "level": 40, "exception": {"values": [{"value": " aaaieaa  a iaa", "type": "ValueError", "module": "builtins", "stacktrace": {"frames": [{"abs_path": "/virtualenv/lib/python3.6/site-packages/raven/base.py", "filename": "raven/base.py", "module": "raven.base", "function": "make_decorator", "lineno": 877, "vars": {"exceptions": ["<class 'Exception'>"], "self": "<raven.base.Client object at 0x108b3ab00>", "kwargs": {}}, "pre_context": ["", "        # In python3.2 contextmanager acts both as contextmanager and decorator", "        @contextlib.contextmanager", "        def make_decorator(exceptions):", "            try:"], "context_line": "                yield", "post_context": ["            except exceptions:", "                self.captureException(**kwargs)", "                raise", "", "        decorator = make_decorator(exceptions)"]}, {"abs_path": "/code/gore/tests/test_send.py", "filename": "gore/tests/test_send.py", "module": "gore.tests.test_send", "function": "test_exception_capture", "lineno": 32, "vars": {"message": "' aaaieaa  a iaa'", "raven_with_project": "<raven.base.Client object at 0x108b3ab00>"}, "pre_context": ["@pytest.mark.django_db", "def test_exception_capture(raven_with_project):", "    message = get_random_string(15, 'iaeoi  ')", "    with pytest.raises(ValueError):", "        with raven_with_project.capture_exceptions():"], "context_line": "            raise ValueError(message)", "post_context": ["    event = raven_with_project.project.event_set.first()", "    assert event.message.endswith(message)", "    assert event.type == 'exception'", "", ""]}]}}]}, "server_name": "Gaea.local", "modules": {"python": "3.6.0"}, "message": "ValueError:  aaaieaa  a iaa", "project": "1", "timestamp": "2017-07-24T16:33:57Z", "time_spent": null, "event_id": "cd551b5c67d84e91a6671c8a147c0e7c", "platform": "python", "sdk": {"name": "raven-python", "version": "6.1.0"}, "repos": {}}
""".strip()
message_payload = """
{"tags": {}, "extra": {"sys.argv": ["'/virtualenv/bin/py.test'", "'gore'", "'-vvv'", "'--cov'", "'.'", "'--cov-report'", "'html'"]}, "sentry.interfaces.Message": {"message": " iio ieeoae o  ", "params": [], "formatted": null}, "message": " iio ieeoae o  ", "level": 40, "server_name": "Gaea.local", "modules": {"python": "3.6.0"}, "project": "1", "timestamp": "2017-07-24T16:33:56Z", "time_spent": null, "event_id": "c0fbbfc2da9d43d8b20c2b74a8bf3dea", "platform": "python", "sdk": {"name": "raven-python", "version": "6.1.0"}, "repos": {}}
""".strip()
