# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gore', '0002_event'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotifierEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('error', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gore.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotifier',
            fields=[
                ('notifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gotify.Notifier')),
                ('emails', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('gotify.notifier',),
        ),
        migrations.CreateModel(
            name='SlackNotifier',
            fields=[
                ('notifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gotify.Notifier')),
                ('webhook_url', models.URLField()),
                ('message_header_suffix', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Slack notifier',
                'verbose_name_plural': 'Slack notifiers',
            },
            bases=('gotify.notifier',),
        ),
        migrations.AddField(
            model_name='notifiereventlog',
            name='notifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='gotify.Notifier'),
        ),
        migrations.AddField(
            model_name='notifier',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_gotify.notifier_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='notifier',
            name='projects',
            field=models.ManyToManyField(blank=True, to='gore.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='notifiereventlog',
            unique_together=set([('notifier', 'event')]),
        ),
    ]
