# Generated by Django 4.0.3 on 2022-05-27 07:25

import django.db.models.deletion
from django.db import migrations, models

import gotify.utils


class Migration(migrations.Migration):
    dependencies = [
        ('gotify', '0002_poly_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, validators=[gotify.utils.is_valid_regex])),
                (
                    'notifier',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='excludes', to='gotify.notifier'
                    ),
                ),
            ],
        ),
    ]
