name: Build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    env:
      DEBUG: "1"
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - '3.8'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: flake8
      - run: py.test -vvv --cov .
      - run: 'bash <(curl -s https://codecov.io/bash)'
